version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show current directory
          command: pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      # - runn
      #     name: Lint
      #     command: yarn lint -- --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: Testing
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: yarn test:ci
      - store_test_results:
          path: reports/junit
      - run:
          name: Coverage
          command: yarn test -- --coverage
      - store_artifacts:
          path: coverage
          destination: coverage
      - run:
          name: Building
          command: yarn build
      - save_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
            - package.json
            - firebase.json
            - .firebaserc
  deploy:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/project
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
